services:
  php:
    build:
      secrets:
        - composer-auth
    restart: unless-stopped
    environment:
      SERVER_NAME: :80 # disable https for traefik > container
    volumes:
      - .docker/caddy/data:/data
      - .docker/caddy/config:/config
      - .storage:/storage
    networks: # need to (re)write all (no merge for networks)
      - app-net
      - puppeteer-net
      - traefik-net

  db:
    restart: unless-stopped

networks:
  traefik-net:
    external: true

secrets:
  composer-auth:
    file: .docker/.composer-auth.json
