services:
  php:
    build:
      secrets:
        - composer-auth
    restart: unless-stopped
    environment:
      SERVER_NAME: :80 # disable https for traefik > container
    volumes:
      - .storage:/storage
    networks: # need to (re)write all (no merge for networks)
      - app-net
      - puppeteer-net
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${CONTAINER_NAME}-https.rule=Host(`${SERVER_NAME}`)"
      - "traefik.http.routers.${CONTAINER_NAME}-https.entrypoints=websecure"
      - "traefik.http.services.${CONTAINER_NAME}.loadbalancer.server.port=80"

  db:
    restart: unless-stopped

networks:
  traefik-net:
    external: true

secrets:
  composer-auth:
    file: .docker/.composer-auth.json
